---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-paul-lh-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-paul-lh
spec:
  type: ClusterIP
  ports:
    - port: 12005
      protocol: UDP
      targetPort: 12005
      name: port-12005
    - port: 13005
      protocol: TCP
      targetPort: 13005
      name: port-13005
    - port: 15005
      protocol: TCP
      targetPort: 15005
      name: port-15005
  selector:
    app: ssv-node-paul-lh
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: ssv-node-paul-lh
  name: ssv-node-paul-lh
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-paul-lh
  template:
    metadata:
      labels:
        app: ssv-node-paul-lh
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-node-paul-lh
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12005
          name: port-12005
          protocol: UDP
          hostPort: 12005            
        - containerPort: 13005
          name: port-13005
          hostPort: 13005
        - containerPort: 15005
          name: port-15005
          hostPort: 15005
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: ETH_1_ADDR
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth1_addr
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: ENR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: enr_key
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: LOG_LEVEL
          value: "info"
        - name: DB_REPORTING
          value: "false"
        - name: PUBSUB_TRACE
          value: "false"
        - name: P2P_LOG
          value: "false"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: GENESIS_EPOCH
          value: "1"
        - name: DB_PATH
          value: "./data/db-shifu-v3"
        - name: METRICS_API_PORT
          value: "15005"
        - name: ENABLE_PROFILE
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-paul-lh
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-paul-lh
      volumes:
      - name: ssv-node-paul-lh
        persistentVolumeClaim:
          claimName: ssv-node-paul-lh
      - name: ssv-cm-validator-options-paul-lh
        configMap:
          name: ssv-cm-validator-options-paul-lh
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true   
