---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-cluster-2-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-cluster-2
spec:
  type: ClusterIP
  ports:
    - port: 12010
      protocol: UDP
      targetPort: 12010
      name: port-12010
    - port: 13010
      protocol: TCP
      targetPort: 13010
      name: port-13010
    - port: 15010
      protocol: TCP
      targetPort: 15010
      name: port-15010
  selector:
    app: ssv-node-cluster-2
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: ssv-node-cluster-2
  name: ssv-node-cluster-2
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-cluster-2
  template:
    metadata:
      labels:
        app: ssv-node-cluster-2
    spec:
      containers:
      - name: ssv-node-cluster-2
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu: {{ .Values.resources.limits_node_2.cpu }}
            memory: {{ .Values.resources.limits_node_2.mem }}            
        command: ["make", "start-node"]
        ports:
        - containerPort: 12010
          name: port-12010
          protocol: UDP
          hostPort: 12010            
        - containerPort: 13010
          name: port-13010
          hostPort: 13010
        - containerPort: 15010
          name: port-15010
          hostPort: 15010
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: bootnodes
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key_v2
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version_v2
              optional: true
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_REPORTING
          value: "false"
        - name: DEBUG_SERVICES
          value: "ssv/protocol*"
        - name: PUBSUB_TRACE
          value: "false"
        - name: P2P_LOG
          value: "false"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: DB_PATH
          value: "./data/db"
        - name: METRICS_API_PORT
          value: "15010"
        - name: ENABLE_PROFILE
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-8
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-ssv-node-cluster-2
      volumes:
      - name: ssv-node-8
        persistentVolumeClaim:
          claimName: ssv-node-8
      - name: ssv-cm-validator-options-ssv-node-cluster-2
        configMap:
          name: ssv-cm-validator-options-ssv-node-cluster-2
      hostNetwork: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
