version: '3.5'

x-base:
  &default-base
  build:
    context: .
    dockerfile: Dockerfile
  image: ssvnode:latest
  command: make BUILD_PATH=/go/bin/ssvnode start-node
  network_mode: host
#  networks:
#    - bloxapp-docker
  restart: always
  environment:
    CONFIG_PATH: ./config/config.yaml

x-base-dev:
  &default-dev
  << : *default-base
  image: ssvnode-debug:latest
  build:
    context: .
    dockerfile: dev.Dockerfile
  command:  air
  environment:
    RUN_CMD: start-node
  security_opt:
    - "seccomp:unconfined"
  cap_add:
    - SYS_PTRACE
  volumes:
    - ./:/go/src/github.com/bloxapp/ssv

services:
  ssv-node-1:
    <<: *default-base
    container_name: ssv-node-1
    environment:
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share1.yaml

  ssv-node-2:
    <<: *default-base
    container_name: ssv-node-2
    environment:
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share2.yaml

  ssv-node-3:
    <<: *default-base
    container_name: ssv-node-3
    environment:
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share3.yaml

  ssv-node-4:
    <<: *default-base
    container_name: ssv-node-4
    environment:
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share4.yaml

  exporter-node:
    <<: *default-base
    container_name: exporter-node
    command: make start-exporter
    environment:
      CONFIG_PATH: ./config/config.exporter.yaml


  ssv-node-1-dev:
    << : *default-dev
    container_name: ssv-node-1-dev
#    ports:
#      - 40005:40005
    environment:
      RUN_CMD: start-node
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40005
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share1.yaml

  ssv-node-2-dev:
    << : *default-dev
    container_name: ssv-node-2-dev
#    ports:
#      - 40006:40006
    environment:
      RUN_CMD: start-node
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40006
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share2.yaml

  ssv-node-3-dev:
    << : *default-dev
    container_name: ssv-node-3-dev
#    ports:
#      - 40007:40007
    environment:
      RUN_CMD: start-node
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40007
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share3.yaml

  ssv-node-4-dev:
    << : *default-dev
    container_name: ssv-node-4-dev
#    ports:
#      - 40008:40008
    environment:
      RUN_CMD: start-node
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40008
      CONFIG_PATH: ./config/config.yaml
      SHARE_CONFIG: ./config/share4.yaml

  exporter-node-dev:
    << : *default-dev
    container_name: exporter-node-dev
#    ports:
#      - 40009:40009
    environment:
      RUN_CMD: start-exporter
      BUILD_PATH: /bin/tmp/ssv
      DEBUG_PORT: 40009
      CONFIG_PATH: ./config/config.exporter.yaml

  prometheus:
    image: prom/prometheus:v2.24.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - data_prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - 9090:9090
    restart: always

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - data_grafana:/var/lib/grafana

#networks:
#  bloxapp-docker:
#    driver: bridge
#    name: bloxapp-docker

volumes:
  data_prometheus:
  data_grafana: