---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-cluster-d-3-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: ssv-node-cluster-d-3
spec:
  type: ClusterIP
  ports:
    - port: 12303
      protocol: UDP
      targetPort: 12303
      name: port-12303
    - port: 13303
      protocol: TCP
      targetPort: 13303
      name: port-13303
    - port: 15303
      protocol: TCP
      targetPort: 15303
      name: port-15303
    - port: 16303
      protocol: TCP
      targetPort: 16303
      name: port-16303
  selector:
    app: ssv-node-cluster-d-3
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: ssv-node-cluster-d-3
  name: ssv-node-cluster-d-3
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-cluster-d-3
  template:
    metadata:
      labels:
        app: ssv-node-cluster-d-3
    spec:
      containers:
      - name: ssv-node-cluster-d-3
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        resources:
          limits:
            cpu:  {{ .Values.resources.limits_node_3.cpu }}
            memory: {{ .Values.resources.limits_node_3.mem }}            
        command: ["make", "start-node"]
        ports:
        - containerPort: 12303
          name: port-12303
          protocol: UDP
          hostPort: 12303            
        - containerPort: 13303
          name: port-13303
          hostPort: 13303
        - containerPort: 15303
          name: port-15303
          hostPort: 15303
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_REPORTING
          value: "false"
        - name: PUBSUB_TRACE
          value: "false"
        - name: P2P_LOG
          value: "false"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: DB_PATH
          value: "./data/db"
        - name: METRICS_API_PORT
          value: "15303"
        - name: ENABLE_PROFILE
          value: "true"
        - name: NETWORK_ID
          value: "shifu-v2-stage"
        - name: GENESIS_EPOCH
          value: "152834"
        - name: WS_API_PORT
          value: "16303"
        - name: FULLNODE
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v3-3
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-ssv-node-cluster-d-3
      volumes:
      - name: ssv-node-v3-3
        persistentVolumeClaim:
          claimName: ssv-node-v3-3
      - name: ssv-cm-validator-options-ssv-node-cluster-d-3
        configMap:
          name: ssv-cm-validator-options-ssv-node-cluster-d-3
      hostNetwork: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
