---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssv-node-v2-1
  namespace: ssv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
