---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ssv-node-7
  namespace: ssv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 15Gi
  storageClassName: gp2
