---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-1-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-1
spec:
  type: ClusterIP
  ports:
    - port: 12001
      protocol: UDP
      targetPort: 12001
      name: port-12001
    - port: 13001
      protocol: TCP
      targetPort: 13001
      name: port-13001
    - port: 15001
      protocol: TCP
      targetPort: 15001
      name: port-15001
  selector:
    app: ssv-node-1
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-1
  name: ssv-node-1
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-1
  template:
    metadata:
      labels:
        app: ssv-node-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-node-1
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12001
          name: port-12001
          hostPort: 12001
          protocol: UDP
        - containerPort: 13001
          name: port-13001
          hostPort: 13001
        - containerPort: 15001
          name: port-15001
          hostPort: 15001
        env:
          - name: SHARE_CONFIG
            value: "./data1/share.yaml"
          - name: BOOTNODES
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: bootnodes
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "prater"
          - name: CONSENSUS_TYPE
            value: "validation"
          - name: HOST_DNS
            value: ""
          - name: HOST_ADDRESS
            value: ""
          - name: GENESIS_EPOCH
            value: "1"
          - name: DB_PATH
            value: "./data/db-shifu-v3"
          - name: METRICS_API_PORT
            value: "15001"
          - name: ENABLE_PROFILE
            value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-1
        - mountPath: /data1/share.yaml
          subPath: share.yaml
          name: ssv-node-1-cm
      volumes:
      - name: ssv-node-1
        persistentVolumeClaim:
          claimName: ssv-node-1
      - name: ssv-node-1-cm
        configMap:
          name: ssv-node-1-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
