---
apiVersion: v1
kind: Service
metadata:
  name: ssv-exporter-holesky
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-exporter-holesky
spec:
  type: ClusterIP
  ports:
    - port: 12013
      protocol: UDP
      targetPort: 12013
      name: port-12013
    - port: 13013
      protocol: TCP
      targetPort: 13013
      name: port-13013
    - port: 14013
      protocol: TCP
      targetPort: 14013
      name: port-14013
    - port: 15013
      protocol: TCP
      targetPort: 15013
      name: port-15013
    - port: 16013
      protocol: TCP
      targetPort: 16013
      name: port-16013
  selector:
    app: ssv-exporter-holesky
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-exporter-holesky
  name: ssv-exporter-holesky
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-exporter-holesky
  template:
    metadata:
      labels:
        app: ssv-exporter-holesky
    spec:
      containers:
        - name: ssv-exporter-holesky
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_EXPORTER_CPU_LIMIT
              memory: REPLACE_EXPORTER_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12013
              name: port-12013
              hostPort: 12013
              protocol: UDP
            - containerPort: 13013
              name: port-13013
              hostPort: 13013
            - containerPort: 14013
              name: port-14013
              hostPort: 14013
            - containerPort: 15013
              name: port-15013
              hostPort: 15013
            - containerPort: 16013
              name: port-16013
              hostPort: 16013
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv.*"
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: DB_PATH
              value: "./data/db-holesky-stage"
            - name: NETWORK
              value: "holesky-stage"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15013"
            - name: SSV_API_PORT
              value: "16013"
            - name: ENABLE_PROFILE
              value: "true"
            - name: UDP_PORT
              value: "12013"
            - name: TCP_PORT
              value: "13003"
            - name: WS_API_PORT
              value: "14013"
            - name: FULLNODE
              value: "true"
            - name: EXPORTER
              value: "true"
            - name: DISCOVERY_TRACE
              value: "false"
            - name: PUBSUB_TRACE
              value: "false"
            - name: SUBNETS
              value: "0xffffffffffffffffffffffffffffffff"
          volumeMounts:
            - mountPath: /data
              name: ssv-exporter-holesky
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-exporter-holesky-cm
      volumes:
        - name: ssv-exporter-holesky
          persistentVolumeClaim:
            claimName: ssv-exporter-holesky
        - name: ssv-exporter-holesky-cm
          configMap:
            name: ssv-exporter-holesky-cm
      hostNetwork: true
