global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: golang 
    metrics_path: /metrics
    static_configs:
      - targets:
        - ssv-node-1:15000
        - ssv-node-2:15000
        - ssv-node-3:15000
        - ssv-node-4:15000

