---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-cluster-c-4-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: ssv-node-cluster-c-4
spec:
  type: ClusterIP
  ports:
    - port: 12012
      protocol: UDP
      targetPort: 12012
      name: port-12012
    - port: 13012
      protocol: TCP
      targetPort: 13012
      name: port-13012
    - port: 15012
      protocol: TCP
      targetPort: 15012
      name: port-15012
  selector:
    app: ssv-node-cluster-c-4
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  labels:
    app: ssv-node-cluster-c-4
  name: ssv-node-cluster-c-4
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-cluster-c-4
  template:
    metadata:
      labels:
        app: ssv-node-cluster-c-4
    spec:
      containers:
      - name: ssv-node-cluster-c-4
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: {{ .Values.resources.limits_node_4.cpu }}
            memory: {{ .Values.resources.limits_node_4.mem }}            
        command: ["make", "start-node"]
        ports:
        - containerPort: 12012
          name: port-12012
          protocol: UDP
          hostPort: 12012            
        - containerPort: 13012
          name: port-13012
          hostPort: 13012
        - containerPort: 15012
          name: port-15012
          hostPort: 15012
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: LOG_LEVEL
          value: "debug"
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: LOGGER_LEVEL
          value: "debug"
        - name: DB_PATH
          value: "./data/db-v3"
        - name: DB_REPORTING
          value: "false"
        - name: METRICS_API_PORT
          value: "15012"
        - name: ENABLE_PROFILE
          value: "true"
        - name: DISCOVERY_TRACE
          value: 'false'
        - name: PUBSUB_TRACE
          value: 'false'
        - name: NETWORK_ID
          value: "shifu-v2-stage"
        - name: GENESIS_EPOCH
          value: "152834"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-12
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-ssv-node-cluster-c-4
      volumes:
      - name: ssv-node-12
        persistentVolumeClaim:
          claimName: ssv-node-12
      - name: ssv-cm-validator-options-ssv-node-cluster-c-4
        configMap:
          name: ssv-cm-validator-options-ssv-node-cluster-c-4
      hostNetwork: true
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
