# List of approved change IDs to ignore.
ApprovedChanges: []

# Identifiers to ignore during comparison.
IgnoredIdentifiers:
  - logger

# Package names that should be reduced to their last component.
ReducedPackageNames:
  - ssv
  - qbft

# Pairs of packages to compare across the codebases.
Comparisons:
  - Packages:
      Left:
        - ./protocol/v2/ssv/runner
      Right:
        - ./ssv
    # User-defined hints for symbol matching. Maps from Left to Right.
    Hints:
      ReconstructSignature: PartialSigContainer.ReconstructSignature

  - Packages:
      Left:
        - protocol/v2/qbft/controller
        - protocol/v2/qbft/instance
      Right:
        - ./qbft
