---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssv-exporter
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
    - "ws-exporter.REPLACE_DOMAIN_SUFFIX"
  gateways:
    - ssv-exporter
  http:
    - route:
        - destination:
            host: ssv-exporter
            port:
              number: 14000
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: ssv-exporter
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway-int
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "ws-exporter.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: ssv-exporter
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-exporter
spec:
  type: ClusterIP
  ports:
    - port: 12000
      protocol: UDP
      targetPort: 12000
      name: port-12000
    - port: 13000
      protocol: TCP
      targetPort: 13000
      name: port-13000
    - port: 14000
      protocol: TCP
      targetPort: 14000
      name: port-14000
    - port: 15000
      protocol: TCP
      targetPort: 15000
      name: port-15000
  selector:
    app: ssv-exporter
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-exporter
  name: ssv-exporter
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-exporter
  template:
    metadata:
      labels:
        app: ssv-exporter
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
        - name: ssv-exporter
          image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
          imagePullPolicy: Always
          resources:
            limits:
              cpu: REPLACE_EXPORTER_CPU_LIMIT
              memory: REPLACE_EXPORTER_MEM_LIMIT
          command: ["make", "start-node"]
          ports:
            - containerPort: 12000
              name: port-12000
              hostPort: 12000
              protocol: UDP
            - containerPort: 13000
              name: port-13000
              hostPort: 13000
            - containerPort: 14000
              name: port-14000
              hostPort: 14000
            - containerPort: 15000
              name: port-15000
              hostPort: 15000
          env:
            - name: SHARE_CONFIG
              value: "./data/share.yaml"
            - name: CONFIG_PATH
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: config_path
            - name: BOOTNODES
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: boot_node
            - name: REGISTRY_CONTRACT_ADDR_KEY
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: smart_contract_addr_key
            - name: ETH_1_SYNC_OFFSET
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: eth_1_sync_offset
                  optional: true
            - name: ABI_VERSION
              valueFrom:
                secretKeyRef:
                  name: config-secrets
                  key: abi_version
                  optional: true
            - name: LOG_LEVEL
              value: "debug"
            - name: DEBUG_SERVICES
              value: "ssv.*"
            - name: DISCOVERY_TYPE_KEY
              value: "discv5"
            - name: NETWORK
              value: "prater"
            - name: DB_PATH
              value: "./data/db-v3-shifu"
            - name: NETWORK_ID
              value: "0x00003011"
            - name: DB_REPORTING
              value: "false"
            - name: METRICS_API_PORT
              value: "15000"
            - name: ENABLE_PROFILE
              value: "true"
            - name: GENERATE_OPERATOR_KEY
              value: "true"
            - name: UDP_PORT
              value: "12000"
            - name: TCP_PORT
              value: "13000"
            - name: WS_API_PORT
              value: "14000"
            - name: FULLNODE
              value: "true"
            - name: EXPORTER
              value: "true"
            - name: GENESIS_EPOCH
              value: "1"
            - name: PERMISSIONED_ACTIVE_SLOT
              value: "5657651"
            - name: PERMISSIONED_DEACTIVE_SLOT
              value: "7464639"
            - name: WHITELISTED_KEYS
              value: "LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBeXMvMGtYNkNaWjZrQjZ4Rk5FeDgKMDdyOURjUE5OWWo2NGJtZEJ5WVhJNzZiaCtvSndzenNSdm1zcGgrQ1kvVTB4enQxOEo1UnV3MzF2azB0UkkvSwpZdzc1Z3A5L285UU9WM09sZ010cEoxV0F4aVBqKzlNcUcwUEpaZGs0ZThnRmZBT2FFVittcDJhMXhsUVNBMnVwCkZLZVlwYTY0bHNBei9vWURJczZzbnVJdnpBeHRhbkFLTHZJUy9pTHU5YW14OHBpNXN2WUFhQURKN2EyRTc5S08KdCtRNWpxSURjbzRjTGlKWUU2SURseENnTnFUVnhFcU5tVWVQQ0NwUVhRZlN0NDZpYlBoc2U2TDZ6WkJYNXZTQQpUUGNPOWtVN2cxY2w2TFl4ZW5jY3RadTJ4alpsdGJTWGMzMmt4VnhWY3N4N1pRMlBWYk5QQzFNdndDU1h1eDNoCnZRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K,LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbk9aQzNieDkyUE50WU93VnpDa2IKa3djZk84VGRsaW1vYjNzTEZtUE1VTzhNai9IUEp1N2RUU1JpMWpkTDZQNVNLbVNtMzl2cXdIRURxM3dtQzFjVwpsTzlTWlg5bDNORDNmM1VBN1JIK283WUFRa0VpakVTMUE0RUVmOTdKSkdqdE1SUTExRWFpelZkUnVSamRxU1RSClVIdE80Z3ZZK0NGTnEzSDZOdXh2OFVmL2lOV3ZyQWxleDdzWFlzUHF6SUQveHR6UGJGbXduZlE1bC9kUlgwYUEKYkpLVzJraElBdmpxSitkam5PMWdkWE9zc0xQZEFHM3pySkdJQnBWenpIaERtRUVmSVFrQUd5Mi9WYVBkcHd3dQpCNTlNRGJ2TmtLakdWR1c1VGl4R2hzaWN6Mmh4b3dhSlJjaHF1V042djZrcEpPTEFUYVkySHMzL1pSTlNwRmZJCjFRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K"
            - name: DISCOVERY_TRACE
              value: "false"
            - name: PUBSUB_TRACE
              value: "false"
            - name: SUBNETS
              value: "0xffffffffffffffffffffffffffffffff"
          volumeMounts:
            - mountPath: /data
              name: ssv-exporter
            - mountPath: /data/share.yaml
              subPath: share.yaml
              name: ssv-exporter-cm
      volumes:
        - name: ssv-exporter
          persistentVolumeClaim:
            claimName: ssv-exporter
        - name: ssv-exporter-cm
          configMap:
            name: ssv-exporter-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
