---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-v3-4-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-v3-4
spec:
  type: ClusterIP
  ports:
    - port: 12304
      protocol: UDP
      targetPort: 12304
      name: port-12304
    - port: 13304
      protocol: TCP
      targetPort: 13304
      name: port-13304
    - port: 15304
      protocol: TCP
      targetPort: 15304
      name: port-15304
  selector:
    app: ssv-node-v3-4
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-v3-4
  name: ssv-node-v3-4
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-v3-4
  template:
    metadata:
      labels:
        app: ssv-node-v3-4
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-node-v3-4
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12304
          name: port-12304
          protocol: UDP
          hostPort: 12304
        - containerPort: 13304
          name: port-13304
          hostPort: 13304
        - containerPort: 15304
          name: port-15304
          hostPort: 15304
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_REPORTING
          value: "false"
        - name: PUBSUB_TRACE
          value: "false"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: DB_PATH
          value: "./data/db-v3-shifu"
        - name: NETWORK_ID
          value: "0x00003011"
        - name: METRICS_API_PORT
          value: "15304"
        - name: ENABLE_PROFILE
          value: "true"
        - name: GENESIS_EPOCH
          value: "152834"
        - name: BUILDER_PROPOSALS
          value: "true"
        - name: PERMISSIONED_ACTIVE_SLOT
          value: "5657651"
        - name: PERMISSIONED_DEACTIVE_SLOT
          value: "1117464639"
        - name: WHITELISTED_KEYS
          value: "LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBd01Lck9lU1ZzMDRaSk00OFZuZGgKMmJqVmtSMFRiblZxZVBrZVA4L3RDMUVOTFhHYW5zb0cvUzRYdEQ3Y25zbE1Dekwvb0RuTFZLL2lBVndtelNJQQpUZTZOWXdMY3hQVzhiNlo2d0ZBZ0RjSm1ZeVBYRUxYMGJ1UWhOL01ZSFE0bnJvRlpwdmRhUXBGS0w3Tjk1cHhzCnlkeXArUmJjVzcyWnFjamlmR1cvVytsblpzZStmVjRlODU3a1pSY29UQUJHdGxsQ1p0N3BNeGU4blYxSmRFaEoKenFSNDdabjQ0SE4zVUZIbFFSMjBTNWxkSlRzSFdkMExJcjNlYmJWSnV0Uzd2ZmxEbThYOWhoUXErYnpjZ2JQOQplejlZTjVFdzRaRE8xcGFkVlkzOFdiVzFEZWxoUkpLTFNhRjN0RXlpZE1mNkk2bmJJekRQVWpIZ1lYSjZLQ3I5CjJ3SURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K,LS0tLS1CRUdJTiBSU0EgUFVCTElDIEtFWS0tLS0tCk1JSUJJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBUThBTUlJQkNnS0NBUUVBbk9aQzNieDkyUE50WU93VnpDa2IKa3djZk84VGRsaW1vYjNzTEZtUE1VTzhNai9IUEp1N2RUU1JpMWpkTDZQNVNLbVNtMzl2cXdIRURxM3dtQzFjVwpsTzlTWlg5bDNORDNmM1VBN1JIK283WUFRa0VpakVTMUE0RUVmOTdKSkdqdE1SUTExRWFpelZkUnVSamRxU1RSClVIdE80Z3ZZK0NGTnEzSDZOdXh2OFVmL2lOV3ZyQWxleDdzWFlzUHF6SUQveHR6UGJGbXduZlE1bC9kUlgwYUEKYkpLVzJraElBdmpxSitkam5PMWdkWE9zc0xQZEFHM3pySkdJQnBWenpIaERtRUVmSVFrQUd5Mi9WYVBkcHd3dQpCNTlNRGJ2TmtLakdWR1c1VGl4R2hzaWN6Mmh4b3dhSlJjaHF1V042djZrcEpPTEFUYVkySHMzL1pSTlNwRmZJCjFRSURBUUFCCi0tLS0tRU5EIFJTQSBQVUJMSUMgS0VZLS0tLS0K"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v3-4
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-v3-4
      volumes:
      - name: ssv-node-v3-4
        persistentVolumeClaim:
          claimName: ssv-node-v3-4
      - name: ssv-cm-validator-options-v3-4
        configMap:
          name: ssv-cm-validator-options-v3-4
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
