---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-v3-1-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-v3-1
spec:
  type: ClusterIP
  ports:
    - port: 12301
      protocol: UDP
      targetPort: 12301
      name: port-12301
    - port: 13301
      protocol: TCP
      targetPort: 13301
      name: port-13301
    - port: 15301
      protocol: TCP
      targetPort: 15301
      name: port-15301
    - port: 16301
      protocol: TCP
      targetPort: 16301
      name: port-16301
  selector:
    app: ssv-node-v3-1
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-v3-1
  name: ssv-node-v3-1
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-v3-1
  template:
    metadata:
      labels:
        app: ssv-node-v3-1
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
      containers:
      - name: ssv-node-v3-1
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12301
          name: port-12301
          protocol: UDP
          hostPort: 12301
        - containerPort: 13301
          name: port-13301
          hostPort: 13301
        - containerPort: 15301
          name: port-15301
          hostPort: 15301
        env:
        - name: SHARE_CONFIG
          value: "./data/share.yaml"
        - name: SSV_NUM_CPU
          value: 2
        - name: CONFIG_PATH
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: config_path
        - name: BOOTNODES
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: boot_node
        - name: REGISTRY_CONTRACT_ADDR_KEY
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: smart_contract_addr_key
        - name: ETH_1_SYNC_OFFSET
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: eth_1_sync_offset
              optional: true
        - name: ABI_VERSION
          valueFrom:
            secretKeyRef:
              name: config-secrets
              key: abi_version
              optional: true
        - name: DEBUG_SERVICES
          value: "ssv/*."
        - name: LOG_LEVEL
          value: "debug"
        - name: DB_REPORTING
          value: "false"
        - name: PUBSUB_TRACE
          value: "false"
        - name: DISCOVERY_TYPE_KEY
          value: "discv5"
        - name: NETWORK
          value: "prater"
        - name: CONSENSUS_TYPE
          value: "validation"
        - name: HOST_DNS
          value: ""
        - name: HOST_ADDRESS
          value: ""
        - name: DB_PATH
          value: "./data/db-v3-shifu"
        - name: NETWORK_ID
          value: "0x00003011"
        - name: METRICS_API_PORT
          value: "15301"
        - name: ENABLE_PROFILE
          value: "true"
        - name: GENESIS_EPOCH
          value: "152834"
        - name: WS_API_PORT
          value: "16301"
        - name: FULLNODE
          value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-v3-1
        - mountPath: /data/share.yaml
          subPath: share.yaml
          name: ssv-cm-validator-options-v3-1
      volumes:
      - name: ssv-node-v3-1
        persistentVolumeClaim:
          claimName: ssv-node-v3-1
      - name: ssv-cm-validator-options-v3-1
        configMap:
          name: ssv-cm-validator-options-v3-1
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
