global:
  LogLevel: info

db:
  Path: ./data/db
  Type: badger-db

eth2:
  BeaconNodeAddr: prater-4000-ext.stage.bloxinfra.com:80
ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

OperatorPrivateKey:
eth1:
  ETH1Addr: ws://eth1-ws.stage.bloxinfra.com/ws
p2p:
  HostAddress: example.ip
  TcpPort:
  UdpPort:
  DiscoveryType: mdns

bootnode:
  ExternalIP:
  PrivateKey:
