global:
  LogLevel: debug
  DebugServices: ".*"

db:
  Path: ./data/db

eth2:
  BeaconNodeAddr: http://prater-standalone.stage.bloxinfra.com:3500
  Network: prater

eth1:
  # ETH1 node WebSocket address
  ETH1Addr: "ws://eth1-2-testnet-stage-ws.blockchain.bloxinfra.com"
  RegistryContractAddr: "0xb9e155e65B5c4D66df28Da8E9a0957f06F11Bc04"

p2p:
  Bootnodes: ""
  P2pLog: true
  # Subnets: "0x0000000000000000ffffffffffffffff" # 64-127
  Subnets: "0x00000000000000000000001000000000" # 92
  # Subnets: "0xffffffffffffffffffffffffffffffff"
  # replace with your ip
#  HostAddress: example.ip
#  TcpPort:
#  UdpPort:
# mdns for local network setup
#  DiscoveryType: mdns

ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s
    FullNode: true
    FullNodeNonCommittee: true

GenerateOperatorPrivateKey: true

bootnode:
  ExternalIP:
  PrivateKey:

LocalEventsPath: ./config/events.yaml
WebSocketAPIPort: 16000
