global:
  LogLevel: info
  LogFilePath: ./data/debug.log

db:
  Path: ./data/db

eth2:
  BeaconNodeAddr: example.url

eth1:
  # ETH1 node WebSocket address
  ETH1Addr: example.url
  RegistryContractAddr: example.address

p2p:
  # replace with your ip
#  HostAddress: example.ip
#  TcpPort:
#  UdpPort:
# mdns for local network setup
#  Discovery: mdns

ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

OperatorPrivateKey:

bootnode:
  ExternalIP:
  PrivateKey:

LocalEventsPath: # path to local events. used for running the node with custom local events
