global:
  LogLevel: info

db:
  Path: ./data/db
  Type: badger-db

ssv:
  GenesisEpoch:
  DutyLimit: 32
  ValidatorOptions:
    SignatureCollectionTimeout: 5s

OperatorPrivateKey:
BeaconNodeAddr: prater-4000.stage.bloxinfra.com:80

eth1:
  ETH1Addr: ws://eth1-ws.stage.bloxinfra.com/ws

p2p:
  HostAddress: example.ip
  TcpPort:
  UdpPort:

bootnode:
  ExternalIP:
  PrivateKey:
