global:
  LogLevel: debug

db:
  Path: ./data/db/exporter
  Type: badger-db

BeaconNodeAddr: prater-4000.stage.bloxinfra.com:80
ETH1Addr: ws://eth1-ws.stage.bloxinfra.com/ws

network:
  HostAddress: 84.110.33.146
  Enr: enr:-LK4QHVq6HEA2KVnAw593SRMqUOvMGlkP8Jb-qHn4yPLHx--cStvWc38Or2xLcWgDPynVxXPT9NWIEXRzrBUsLmcFkUBh2F0dG5ldHOIAAAAAAAAAACEZXRoMpD1pf1CAAAAAP__________gmlkgnY0gmlwhDbUHcyJc2VjcDI1NmsxoQO8KQz5L1UEXzEr-CXFFq1th0eG6gopbdul2OQVMuxfMoN0Y3CCE4iDdWRwgg-g

