db:
  Path: ./data/db/1
  Type: badger-db
ssv:

  ValidatorOptions:
    Shares:
      - NodeID: <node-id>
        PublicKey: <validator-pubkey>
        ShareKey: <share-priv-key>
        Committee:
          <share-pubkey-node1>: <node1-id>
          <share-pubkey-node2>: <node2-id>
          <share-pubkey-node3>: <node3-id>
          <share-pubkey-node4>: <node4-id>
