global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: ssv
    metrics_path: /metrics
    static_configs:
      - targets:
        # change the targets according to your setup
        # - <container_name>:15000
        - ssv-node-1:15001
        - ssv-node-2:15002
        - ssv-node-3:15003
        - ssv-node-4:15004
  - job_name: ssv_health
    metrics_path: /health
    static_configs:
      - targets:
        - ssv-node-1:15001
        - ssv-node-2:15002
        - ssv-node-3:15003
        - ssv-node-4:15004
