---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: boot-node-mainnet
  namespace: REPLACE_NAMESPACE
spec:
  hosts:
  - "boot-node-mainnet.REPLACE_DOMAIN_SUFFIX"
  gateways:
  - boot-node-mainnet
  http:
  - route:
    - destination:
        host: boot-node-mainnet-svc
        port:
          number: 5002
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: boot-node-mainnet
  namespace: REPLACE_NAMESPACE
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "boot-node-mainnet.REPLACE_DOMAIN_SUFFIX"
---
apiVersion: v1
kind: Service
metadata:
  name: boot-node-mainnet-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: boot-node-mainnet
spec:
  type: ClusterIP
  ports:
    - port: 4002
      protocol: UDP
      targetPort: 4002
      name: port-4002
    - port: 5002
      protocol: TCP
      targetPort: 5002
      name: port-5002
  selector:
    app: boot-node-mainnet
---
apiVersion: REPLACE_API_VERSION 
kind: Deployment
metadata:
  labels:
    app: boot-node-mainnet
  name: boot-node-mainnet
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: boot-node-mainnet
  template:
    metadata:
      labels:
        app: boot-node-mainnet
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/role
                operator: In
                values:
                - ssv-boot-node-mainnet
      containers:
      - name: boot-node-mainnet
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG 
        imagePullPolicy: Always
        command: ["make", "start-boot-node"]
        ports:
        - containerPort: 5002
          name: port-5002   
          hostPort: 5002
        env:
          - name: CONFIG_PATH
            value: /config/config.example.yaml
          - name: BOOT_NODE_PRIVATE_KEY
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: boot_node_mainnet_private_key
          - name: BOOT_NODE_EXTERNAL_IP
            valueFrom:
              secretKeyRef:
                name: config-secrets
                key: boot_node_mainnet_external_ip
          - name: TCP_PORT
            value: "5002"
          - name: UDP_PORT
            value: "4002"
        volumeMounts:
        - mountPath: /data/bootnode
          name: boot-node-mainnet
        - mountPath: /data/config.yaml
          name: boot-node-mainnet-cm
      volumes:
      - name: boot-node-mainnet
        persistentVolumeClaim:
          claimName: boot-node-mainnet
      - configMap:
          defaultMode: 420
          name: boot-node-mainnet-cm
        name: boot-node-mainnet-cm
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/role
        operator: Exists         
      hostNetwork: true
