---
apiVersion: v1
kind: Service
metadata:
  name: ssv-node-prater-3-svc
  namespace: REPLACE_NAMESPACE
  labels:
    app: ssv-node-prater-3
spec:
  type: ClusterIP
  ports:
    - port: 12013
      protocol: UDP
      targetPort: 12013
      name: port-12013
    - port: 13013
      protocol: TCP
      targetPort: 13013
      name: port-13013
    - port: 15013
      protocol: TCP
      targetPort: 15013
      name: port-15013
    - port: 16013
      protocol: TCP
      targetPort: 16013
      name: port-16013
  selector:
    app: ssv-node-prater-3
---
apiVersion: REPLACE_API_VERSION
kind: Deployment
metadata:
  labels:
    app: ssv-node-prater-3
  name: ssv-node-prater-3
  namespace: REPLACE_NAMESPACE
spec:
  replicas: REPLACE_REPLICAS
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ssv-node-prater-3
  template:
    metadata:
      labels:
        app: ssv-node-prater-3
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/role
                    operator: In
                    values:
                      - ssv-main
                  - key: beta.kubernetes.io/instance-type
                    operator: In
                    values:
                      - m5a.4xlarge
      containers:
      - name: ssv-node-prater-3
        image: REPLACE_DOCKER_REPO:REPLACE_IMAGETAG
        imagePullPolicy: Always
        resources:
          limits:
            cpu: REPLACE_NODES_CPU_LIMIT
            memory: REPLACE_NODES_MEM_LIMIT
        command: ["make", "start-node"]
        ports:
        - containerPort: 12013
          name: port-12013
          hostPort: 12013
          protocol: UDP
        - containerPort: 13013
          name: port-13013
          hostPort: 13013
        - containerPort: 15013
          name: port-15013
          hostPort: 15013
        - containerPort: 16013
          name: port-16013
          hostPort: 16013
        env:
          - name: SHARE_CONFIG
            value: "./data1/share.yaml"
          - name: LOG_LEVEL
            value: "debug"
          - name: DB_REPORTING
            value: "false"
          - name: PUBSUB_TRACE
            value: "false"
          - name: DISCOVERY_TYPE_KEY
            value: "discv5"
          - name: NETWORK
            value: "jato-v2"
          - name: CONSENSUS_TYPE
            value: "validation"
          - name: HOST_DNS
            value: ""
          - name: HOST_ADDRESS
            value: ""
          - name: DB_PATH
            value: "./data/db-jato-v2"
          - name: METRICS_API_PORT
            value: "15013"
          - name: SSV_API_PORT
            value: "16013"
          - name: ENABLE_PROFILE
            value: "true"
        volumeMounts:
        - mountPath: /data
          name: ssv-node-prater-3
        - mountPath: /data1/share.yaml
          subPath: share.yaml
          name: ssv-node-prater-3-cm
      volumes:
      - name: ssv-node-prater-3
        persistentVolumeClaim:
          claimName: ssv-node-prater-3
      - name: ssv-node-prater-3-cm
        configMap:
          name: ssv-node-prater-3-cm
      tolerations:
        - effect: NoSchedule
          key: kubernetes.io/role
          operator: Exists
      hostNetwork: true
