name: E2E Test

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main
      - stage

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Run e2e.sh
        run: |
          cd ./e2e/
          chmod +x ./run.sh
          ./run.sh
