name: full-test

on:
  push:
    branches:
      - 'main'
      - 'stage'
#      - 'spec-align-qbft'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Full-test
        run: make full-test
