name: Spec tests

on:
  push:
    branches:
      - "main"
      - "stage"
  pull_request:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.1

      - name: Run spec tests
        run: make spec-test
