name: Spec tests

on:
  push:
    branches:
      - "**"

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20.x"

      - name: Run spec tests
        run: make spec-test
