name: Spec tests

on:
  push:
    branches:
      - 'stage'
      - 'main'
      - 'spec-align-qbft'
  pull_request:
    branches: 
      - '**'        

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Run spec tests
        run: make spec-test
