name: unit-test

on:
  push:
    branches: 
      - '**'

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup make
        run: sudo apt-get update && sudo apt-get install make

      - name: Run unit tests
        run: make unit-test
